In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

#import libraries
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import scipy
from scipy import linalg as la
import matplotlib.pyplot as plt

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

<h1>Express Vector</h1>

In [2]:
#create vector
v = np.array([1,2,3,4,5])

print(v)
print(v[0])

[1 2 3 4 5]
1


In [3]:
# vector's size
v.shape

(5,)

In [4]:
#부분벡터(sub vector)
v_sub = v[0:2]
v_sub

array([1, 2])

In [5]:
#zero vector
size = 5
zeros = np.zeros(shape=(size))
zeros

array([0., 0., 0., 0., 0.])

In [6]:
# 단위벡터(unit vector): a value in vector is 1, and the others are 0
e = np.zeros(shape=(3,))
i = 1
e[i] = 1
e

array([0., 1., 0.])

In [7]:
# 1vector : all elements' value are 1
one = np.ones(shape=(3,4))
one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
# vector addition
a = np.array([1,2])
b = np.array([3,4])

a+b

array([4, 6])

In [9]:
#commutative law
a+b == b+a

array([ True,  True])

In [10]:
# combination law
c = np.array([5,6])

(a+b)+c == a+(b+c)

array([ True,  True])

In [11]:
#scalar multiplication
s = 2
a*s

array([2, 4])

<h3>Inner product</h3>
두 벡터의 각 성분끼리의 곱의 합 <br>
$a^Tb =\displaystyle\sum_{i}{(a_i b_i)}$

<h3>Euclidean Norm</h3><br>
벡터의 길이, 크기(magnititude)<br>****
$||a|| = \sqrt{a^Ta} = \sqrt{a_1^2 + ... + a_n^2}$

In [12]:
# inner product(벡터 내적): 두 벡터의 각 성분끼리의 곱의 합
#1.
print(np.sum(a*b))

#2.
print(np.inner(a,b))

#3.
print(np.dot(a,b))

11
11
11


In [13]:
# characters of inner product
print(np.dot(a,b) == np.dot(b,a))
print(np.dot(2*a,b)==2*np.dot(a,b))
print(np.dot(a+b,c)==np.dot(a,c)+np.dot(b,c))

True
True
True


In [14]:
# 내적의 활용
a = np.array([1,2,3])
ones = np.ones(shape=(3,))

##1. 합
print(np.dot(ones,a))

##2.평균
print(np.dot(ones,a)/len(a))

##3.제곱합
print(np.dot(a,a))

6.0
2.0
14


In [15]:
# Euclidean norm: length, magnitude of vector
from scipy import linalg as la

a = np.array([2,3])
la.norm(a)

3.605551275463989

In [16]:
# characteristic of vector norm
a = np.array([-1, 2, 3])
b = np.array([1, -2, 4])

In [17]:
#삼각형의 한 변의 길이는 다른 두 변의 길이의 합보다 작다
la.norm(a+b) <= la.norm(a)+la.norm(b)

True

In [18]:
#길이는 0보다 크거나 작다
la.norm(a) >= 0

True

In [19]:
#orthonormal vector
a1 = np.array([0,0,1]).reshape(-1,1)
a2 = 1/np.sqrt(2)*np.array([1,1,0]).reshape(-1,1)
a3 = 1/np.sqrt(2)*np.array([1,-1,0]).reshape(-1,1)

In [20]:
#norm=1, 열들의 곱
A = np.concatenate((a1,a2,a3),axis=1)
np.round(A.T@A,3)

array([[ 1.,  0.,  0.],
       [ 0.,  1., -0.],
       [ 0., -0.,  1.]])

In [21]:
# 2차원 배열 생성 
A = np.array(np.random.RandomState(123).normal(size=16)).reshape(4,4)
A.round(3)

array([[-1.086,  0.997,  0.283, -1.506],
       [-0.579,  1.651, -2.427, -0.429],
       [ 1.266, -0.867, -0.679, -0.095],
       [ 1.491, -0.639, -0.444, -0.434]])

In [22]:
#행렬의 크기
A = np.random.RandomState(123).randint(1,12,size=12).reshape(3,4)
A.shape

(3, 4)

In [23]:
#열벡터
A[:,0]

array([3, 4, 2])

In [24]:
#행벡터
A[0,:]

array([3, 3, 7, 2])

In [25]:
#행렬의 표기법
A[0,2]

7

In [26]:
#행렬 덧셈
A = np.arange(1,7).reshape(2,3)
B = np.arange(3,9).reshape(2,3)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
B

array([[3, 4, 5],
       [6, 7, 8]])

In [28]:
A+B

array([[ 4,  6,  8],
       [10, 12, 14]])

In [29]:
#행렬의 전치의 성질
A.T + B.T == (A+B).T

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [30]:
#행렬 곱 연산자:@
A @ B.T

array([[ 26,  44],
       [ 62, 107]])

In [31]:
# 행렬 곱 함수: np.matmul
np.matmul(A,B.T)

array([[ 26,  44],
       [ 62, 107]])

In [32]:
B = B.T

In [33]:
# 행렬 곱의 전치
(A@B).T == B.T @ A.T

array([[ True,  True],
       [ True,  True]])

In [34]:
#영행렬
size = 3
np.zeros(shape=(size,size))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
#항등행렬
np.identity(n=size)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
#대각행렬
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [37]:
# 상삼각행렬
np.triu([[1,2,3],[1,2,7],[7,8,5]], k=0)

array([[1, 2, 3],
       [0, 2, 7],
       [0, 0, 5]])

In [38]:
#A^T*A = A*A^T = I 일때 A는 직교행렬(orthogonal matrix)
A = np.array([[1,0],[0,1]])
A

array([[1, 0],
       [0, 1]])

In [39]:
A.T@A

array([[1, 0],
       [0, 1]])

In [40]:
#선형방적식과 후방대입법
A = np.array([[1,1],[1/2, -1]])
XTX = A.T@A
XTX

array([[1.25, 0.5 ],
       [0.5 , 2.  ]])

In [41]:
#QR 분해
Q, R = la.qr(XTX)
R.round(2)

array([[-1.35, -1.21],
       [ 0.  ,  1.67]])

In [42]:
b = np.array([4,2])
np.round(Q.T @ b, 2)

array([-4.46,  0.37])

In [43]:
#하우스 홀더 변환 이해하기
A = np.array([[5,1,5],
             [3,9,8],
             [2,1,4]])
A

array([[5, 1, 5],
       [3, 9, 8],
       [2, 1, 4]])

In [44]:
#첫번째 열벡터 추출
a = A[:,0].reshape(-1,1)
a

array([[5],
       [3],
       [2]])

In [45]:
# 하우스홀더 행렬 Q1 구성
size = A.shape[0]
e1 = np.identity(n=size)[:,0].reshape(-1,1) #단위행렬 생성후 열벡터 생성

#u,v 벡터 구성
u = a - la.norm(a)*e1
u

array([[-1.164414],
       [ 3.      ],
       [ 2.      ]])

In [46]:
v = u/la.norm(u)
v

array([[-0.30732141],
       [ 0.79178387],
       [ 0.52785591]])

In [47]:
#84p